Write-Host "=== DEBUGGING SHOWTIME FILTERING ==="

Write-Host "1. Starting backend with debug logging..."
Start-Process powershell -ArgumentList "-ExecutionPolicy Bypass -Command `"cd .. ; mvn spring-boot:run`"" -NoNewWindow
Write-Host "Waiting for backend to start..."
Start-Sleep -Seconds 30

Write-Host "2. Starting frontend..."
Start-Process powershell -ArgumentList "-ExecutionPolicy Bypass -Command `"npm run dev`"" -WorkingDirectory "frontend" -NoNewWindow
Write-Host "Waiting for frontend to start..."
Start-Sleep -Seconds 15

Write-Host "=== APPLICATION STARTED ==="
Write-Host "Backend: http://localhost:8080"
Write-Host "Frontend: http://localhost:5174"

Write-Host ""
Write-Host "=== DEBUGGING EXPIRED SHOWTIME FILTERING ==="
Write-Host "Current Date/Time: $(Get-Date)"
Write-Host ""
Write-Host "=== TESTING API ENDPOINTS ==="
Write-Host "1. Test movie showtimes:"
Write-Host "   curl http://localhost:8080/api/movie/1/showtimes"
Write-Host ""
Write-Host "2. Test showtime by movie:"
Write-Host "   curl http://localhost:8080/api/showtime/movie/1"
Write-Host ""
Write-Host "3. Test showtime by room:"
Write-Host "   curl http://localhost:8080/api/showtime/room/1"
Write-Host ""
Write-Host "=== EXPECTED DEBUG OUTPUT ==="
Write-Host "Backend console should show:"
Write-Host "[ShowtimeService] Filtering showtimes at: [current time]"
Write-Host "[ShowtimeService] Total showtimes before filtering: X"
Write-Host "[ShowtimeService] Showtime ID: Y, EndTime: [date], IsActive: true/false"
Write-Host "[ShowtimeService] Active showtimes after filtering: Z"
Write-Host ""
Write-Host "=== CHECKING DATABASE ==="
Write-Host "If filtering is not working, check:"
Write-Host "1. Database showtime endTime values"
Write-Host "2. Server timezone vs database timezone"
Write-Host "3. Date format in database"
Write-Host ""
Write-Host "=== MANUAL DATABASE CHECK ==="
Write-Host "Run this SQL to check showtimes:"
Write-Host "SELECT id, start_time, end_time, NOW() as current_time,"
Write-Host "       CASE WHEN end_time > NOW() THEN 'ACTIVE' ELSE 'EXPIRED' END as status"
Write-Host "FROM showtimes"
Write-Host "ORDER BY end_time DESC;"
Write-Host ""
Write-Host "=== FRONTEND DEBUGGING ==="
Write-Host "1. Open browser developer tools"
Write-Host "2. Check Network tab for API calls"
Write-Host "3. Verify API responses contain only active showtimes"
Write-Host "4. Check if frontend is caching old data"
Write-Host ""
Write-Host "Press any key to exit..."
$host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown") | Out-Null

