Write-Host "=== TESTING ACTIVE SHOWTIME DISPLAY ==="

Write-Host "1. Starting backend with active showtime filtering..."
Start-Process powershell -ArgumentList "-ExecutionPolicy Bypass -Command `"cd .. ; mvn spring-boot:run`"" -NoNewWindow
Write-Host "Waiting for backend to start..."
Start-Sleep -Seconds 30

Write-Host "2. Starting frontend..."
Start-Process powershell -ArgumentList "-ExecutionPolicy Bypass -Command `"npm run dev`"" -WorkingDirectory "frontend" -NoNewWindow
Write-Host "Waiting for frontend to start..."
Start-Sleep -Seconds 15

Write-Host "=== APPLICATION STARTED ==="
Write-Host "Backend: http://localhost:8080"
Write-Host "Frontend: http://localhost:5174"

Write-Host ""
Write-Host "=== ACTIVE SHOWTIME DISPLAY FEATURE ==="
Write-Host "This feature shows only active showtimes (endTime > now) for room display:"
Write-Host "1. When selecting cinema -> room -> showtimes"
Write-Host "2. Only showtimes that haven't ended yet"
Write-Host "3. Hide expired showtimes"
Write-Host ""
Write-Host "=== TESTING API ENDPOINTS ==="
Write-Host "1. Debug endpoint (all showtimes):"
Write-Host "   curl http://localhost:8080/api/showtime/debug/all"
Write-Host ""
Write-Host "2. Filtered movie showtimes (active only):"
Write-Host "   curl http://localhost:8080/api/movie/1/showtimes"
Write-Host ""
Write-Host "3. Filtered showtime by movie (active only):"
Write-Host "   curl http://localhost:8080/api/showtime/movie/1"
Write-Host ""
Write-Host "4. Filtered showtime by room (active only):"
Write-Host "   curl http://localhost:8080/api/showtime/room/1"
Write-Host ""
Write-Host "=== EXPECTED BEHAVIOR ==="
Write-Host "Before filtering:"
Write-Host "- Showtime 1: endTime=2025-09-22T20:00, isActive=false (expired)"
Write-Host "- Showtime 2: endTime=2025-09-24T20:00, isActive=true (active)"
Write-Host ""
Write-Host "After filtering:"
Write-Host "- Only Showtime 2 returned (endTime > now)"
Write-Host "- Showtime 1 hidden (already expired)"
Write-Host ""
Write-Host "=== BACKEND LOGGING ==="
Write-Host "Look for logs like:"
Write-Host "[ShowtimeService] Showtime ID: X, StartTime: [time], EndTime: [time], TimeDiff: [ms], IsActive: true/false"
Write-Host ""
Write-Host "=== FRONTEND IMPACT ==="
Write-Host "When user selects:"
Write-Host "1. Cinema -> Room -> Showtimes"
Write-Host "2. Only active showtimes will be displayed"
Write-Host "3. Expired showtimes will be hidden"
Write-Host "4. User can only see bookable showtimes"
Write-Host ""
Write-Host "=== TESTING STEPS ==="
Write-Host "1. Check debug endpoint to see all showtimes"
Write-Host "2. Verify isActive is based on endTime > now"
Write-Host "3. Test filtered endpoints"
Write-Host "4. Confirm only active showtimes are returned"
Write-Host "5. Check frontend shows only active showtimes"
Write-Host ""
Write-Host "Press any key to exit..."
$host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown") | Out-Null
