Write-Host "=== TESTING LOGIN NOTIFICATIONS ==="

Write-Host "1. Starting backend with email verification check..."
Start-Process powershell -ArgumentList "-ExecutionPolicy Bypass -Command `"cd .. ; mvn spring-boot:run`"" -NoNewWindow
Write-Host "Waiting for backend to start..."
Start-Sleep -Seconds 30

Write-Host "2. Starting frontend..."
Start-Process powershell -ArgumentList "-ExecutionPolicy Bypass -Command `"npm run dev`"" -WorkingDirectory "frontend" -NoNewWindow
Write-Host "Waiting for frontend to start..."
Start-Sleep -Seconds 15

Write-Host "=== APPLICATION STARTED ==="
Write-Host "Backend: http://localhost:8080"
Write-Host "Frontend: http://localhost:5174"

Write-Host ""
Write-Host "=== LOGIN NOTIFICATIONS FEATURE ==="
Write-Host "This feature shows colored notifications for login results:"
Write-Host "1. Red notification for errors (3 seconds)"
Write-Host "2. Green notification for success (3 seconds)"
Write-Host "3. Specific error messages for different scenarios"
Write-Host ""
Write-Host "=== NOTIFICATION TYPES ==="
Write-Host "1. Email Verification Error:"
Write-Host "   - Message: 'Hãy xác thực email để đăng nhập'"
Write-Host "   - Color: Red background with red border"
Write-Host "   - Duration: 3 seconds"
Write-Host ""
Write-Host "2. Wrong Password Error:"
Write-Host "   - Message: 'Mật khẩu không chính xác'"
Write-Host "   - Color: Red background with red border"
Write-Host "   - Duration: 3 seconds"
Write-Host ""
Write-Host "3. User Not Found Error:"
Write-Host "   - Message: 'Tên đăng nhập không tồn tại'"
Write-Host "   - Color: Red background with red border"
Write-Host "   - Duration: 3 seconds"
Write-Host ""
Write-Host "4. Login Success:"
Write-Host "   - Message: 'Đăng nhập thành công! Đang chuyển hướng...'"
Write-Host "   - Color: Green background with green border"
Write-Host "   - Duration: 3 seconds"
Write-Host "   - Redirect: After 1.5 seconds"
Write-Host ""
Write-Host "=== TESTING SCENARIOS ==="
Write-Host "1. Test with unverified email:"
Write-Host "   - Login with user that has is_email_verified = 0"
Write-Host "   - Should show red notification: 'Hãy xác thực email để đăng nhập'"
Write-Host ""
Write-Host "2. Test with wrong password:"
Write-Host "   - Login with correct username but wrong password"
Write-Host "   - Should show red notification: 'Mật khẩu không chính xác'"
Write-Host ""
Write-Host "3. Test with non-existent user:"
Write-Host "   - Login with username that doesn't exist"
Write-Host "   - Should show red notification: 'Tên đăng nhập không tồn tại'"
Write-Host ""
Write-Host "4. Test successful login:"
Write-Host "   - Login with verified user and correct password"
Write-Host "   - Should show green notification: 'Đăng nhập thành công!'"
Write-Host "   - Should redirect after 1.5 seconds"
Write-Host ""
Write-Host "=== FRONTEND FEATURES ==="
Write-Host "1. Auto-hide notifications after 3 seconds"
Write-Host "2. Animated notifications with pulse effect"
Write-Host "3. Icons for different notification types"
Write-Host "4. Close button for manual dismissal"
Write-Host "5. Responsive design"
Write-Host ""
Write-Host "=== TESTING STEPS ==="
Write-Host "1. Open browser to http://localhost:5174/login"
Write-Host "2. Try different login scenarios"
Write-Host "3. Observe notification colors and messages"
Write-Host "4. Check auto-hide timing (3 seconds)"
Write-Host "5. Test manual close button"
Write-Host "6. Verify redirect timing for success"
Write-Host ""
Write-Host "=== DATABASE SETUP ==="
Write-Host "To test email verification:"
Write-Host "1. Set user as unverified:"
Write-Host "   UPDATE users SET is_email_verified = 0 WHERE username = 'testuser';"
Write-Host ""
Write-Host "2. Set user as verified:"
Write-Host "   UPDATE users SET is_email_verified = 1 WHERE username = 'testuser';"
Write-Host ""
Write-Host "=== EXPECTED UI BEHAVIOR ==="
Write-Host "1. Notifications appear immediately after login attempt"
Write-Host "2. Red notifications for errors with error icon"
Write-Host "3. Green notifications for success with check icon"
Write-Host "4. Smooth animations and transitions"
Write-Host "5. Notifications disappear automatically after 3 seconds"
Write-Host "6. Success notifications redirect after 1.5 seconds"
Write-Host ""
Write-Host "Press any key to exit..."
$host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown") | Out-Null
