Write-Host "=== TESTING EXPIRED SHOWTIME DISPLAY ==="

Write-Host "1. Starting backend with expired showtime filtering..."
Start-Process powershell -ArgumentList "-ExecutionPolicy Bypass -Command `"cd .. ; mvn spring-boot:run`"" -NoNewWindow
Write-Host "Waiting for backend to start..."
Start-Sleep -Seconds 30

Write-Host "2. Starting frontend..."
Start-Process powershell -ArgumentList "-ExecutionPolicy Bypass -Command `"npm run dev`"" -WorkingDirectory "frontend" -NoNewWindow
Write-Host "Waiting for frontend to start..."
Start-Sleep -Seconds 15

Write-Host "=== APPLICATION STARTED ==="
Write-Host "Backend: http://localhost:8080"
Write-Host "Frontend: http://localhost:5174"

Write-Host ""
Write-Host "=== EXPIRED SHOWTIME DISPLAY FEATURE ==="
Write-Host "This feature shows only expired showtimes (endTime < now) for room display:"
Write-Host "1. When selecting cinema -> room -> showtimes"
Write-Host "2. Only showtimes that have already ended"
Write-Host "3. Hide active/future showtimes"
Write-Host ""
Write-Host "=== TESTING API ENDPOINTS ==="
Write-Host "1. Debug endpoint (all showtimes):"
Write-Host "   curl http://localhost:8080/api/showtime/debug/all"
Write-Host ""
Write-Host "2. Filtered movie showtimes (expired only):"
Write-Host "   curl http://localhost:8080/api/movie/1/showtimes"
Write-Host ""
Write-Host "3. Filtered showtime by movie (expired only):"
Write-Host "   curl http://localhost:8080/api/showtime/movie/1"
Write-Host ""
Write-Host "4. Filtered showtime by room (expired only):"
Write-Host "   curl http://localhost:8080/api/showtime/room/1"
Write-Host ""
Write-Host "=== EXPECTED BEHAVIOR ==="
Write-Host "Before filtering:"
Write-Host "- Showtime 1: endTime=2025-09-22T20:00, isExpired=true"
Write-Host "- Showtime 2: endTime=2025-09-24T20:00, isExpired=false"
Write-Host ""
Write-Host "After filtering:"
Write-Host "- Only Showtime 1 returned (endTime < now)"
Write-Host "- Showtime 2 hidden (still active)"
Write-Host ""
Write-Host "=== BACKEND LOGGING ==="
Write-Host "Look for logs like:"
Write-Host "[ShowtimeService] Showtime ID: X, StartTime: [time], EndTime: [time], TimeDiff: [ms], IsExpired: true/false"
Write-Host ""
Write-Host "=== FRONTEND IMPACT ==="
Write-Host "When user selects:"
Write-Host "1. Cinema -> Room -> Showtimes"
Write-Host "2. Only expired showtimes will be displayed"
Write-Host "3. Active showtimes will be hidden"
Write-Host "4. User can see past showtimes for reference"
Write-Host ""
Write-Host "=== TESTING STEPS ==="
Write-Host "1. Check debug endpoint to see all showtimes"
Write-Host "2. Verify isExpired is based on endTime"
Write-Host "3. Test filtered endpoints"
Write-Host "4. Confirm only expired showtimes are returned"
Write-Host "5. Check frontend shows only expired showtimes"
Write-Host ""
Write-Host "Press any key to exit..."
$host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown") | Out-Null
